version: '3.8'

services:
  adventura-api-dev:
    build: .
    container_name: adventura_api_dev
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-dev:5432/adventura_db
      UNSPLASH_ACCESS_KEY: ${UNSPLASH_ACCESS_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    depends_on:
      - db-dev

  db-dev:
    image: postgres:15-alpine
    container_name: postgres_dev_container
    environment:
      POSTGRES_DB: adventura_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

volumes:
  pgdata_dev: